### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by ryneches** [jiarong/VirSorter2#10]
virsorter2 crashes with too many open files when processing a large (23GB) assembly.

[virsorter_crash.log](https://github.com/jiarong/VirSorter2/files/5449037/virsorter_crash.log)

**Comment by ryneches** [comment]
Upping the file limit to 20,000 postpones the crash until there are 20,000 open files. Manually increasing the file limit is not a acceptable fix, as users have no way to know how many are required and considerable computational resources are wasted in finding out. The number of open files should *never* exceed 1024.

**Comment by jiarong** [comment]
@ryneches Thanks for reporting the bug. Indeed, total opened files needs to be limited. 

As a quick fix, you can find set the following variables in "template-config.yaml" to a much larger number to reduce the number of split files:

CONTIG_BP_PER_SPLIT: 30000000     
FAA_BP_PER_SPLIT: 10000000        
GFF_SEQNUM_PER_SPLIT: 1000   # this is causing your error; increase the number to total sequence number / number of cores for the job

**Comment by simroux** [comment]
Quick additional note: I got a similar problem (I think) but another error. VirSorter2 crashes on some datasets on the line which concatenate all the split results from GFF. That happens when there's more than ~ 1,750 splits, then the bash line ("cat iter-0/NCLDV/all.pdg.gff.splitdir/all.pdg.gff.482.split.prv.ftr iter-0/NCLDV/all.pdg.gff.splitdir/all.pdg.gff.483.split.prv.ftr iter-0/NCLDV/all.pdg.gff.splitdir/all.pdg.gff.484.split.prv.ftr [...]  | awk '!/^seqname      / || !f++' > iter-0/NCLDV/all.pdg.prv.ftr") fails,  probably because it's too long ? Error message is "Error in rule merge_provirus_call_by_group_by_split: [...] (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!"

I'll try with increasing the GFF_SEQNUM_PER_SPLIT, but leaving this here in case it can help anyone else, and also as an additional case for increasing the default GFF_SEQNUM_PER_SPLIT or increasing it automatically based on the number of input contig to never generate more than ~ 1,000 split (to be on the safe side).

**Comment by jiarong** [comment]
@simroux Right, bash command line has a size upper limit.  This bug will be fixed in next update.

**Comment by jiarong** [comment]
This issue should have been fixed now. Splits are all limited to 1k max.
