### ISSUE TITLE
Alternative genetic code

### ISSUE THREAD

**Issue by YuyaKiguchi** [jiarong/VirSorter2#100]
Hi,

Is it possible to assess phage genomes with alternative genetic code?

Thanks,
Yuya

**Comment by jiarong** [comment]
Hi Yuya, it's not supported. Currently, all genes are predicted by `prodigal` using code 11 for bacteria. VirSorter2 is designed for *metagenomes* where many different codes are used in different organisms or viruses, but we have to use the most common code for training the machine learning model. Otherwise, the algorithm became complicated.
