### ISSUE TITLE
when i use virsorter2, i met a question, need some help!!

### ISSUE THREAD

**Issue by liucong0429** [jiarong/VirSorter2#148]
![image](https://user-images.githubusercontent.com/122799028/212689508-19616c84-a268-4e6f-be6d-ada267856eac.png)

just like the picture, it seems something wrong with snakemake??

**Comment by lbooshehri** [comment]
Yes -- I am experiencing the same issue for both dsDNA and ssDNA groups. 
I noticed that I get a warning message after the Step 1 preprocess step (before it fails):

Warning: the following output files of rule gff_feature_by_group were not present when the DAG was created:
{'iter-0/ssDNA/all.pdg.gff.ftr'}
Warning: the following output files of rule gff_feature_by_group were not present when the DAG was created:
{'iter-0/dsDNAphage/all.pdg.gff.ftr'}

.......

Error in rule classify_by_group:
Error in rule classify_by_group:
    jobid: 56
    jobid: 57
    output: iter-0/dsDNAphage/all.pdg.clf
    output: iter-0/ssDNA/all.pdg.clf

:(

**Comment by liucong0429** [comment]
I get the error after the Step 2 preprocess extract-feature finished. i have no idea where is wrong...

**Comment by jiarong** [comment]
Can you check the numpy version installed w/ VirSorter2?
```
conda list numpy
```

**Comment by liucong0429** [comment]
numpy 1.21.2

**Comment by liucong0429** [comment]
> Can you check the numpy version installed w/ VirSorter2?
> 
> ```
> conda list numpy
> ```

I wonder if you have other suggestions for this problem？ thanks a lot

**Comment by morganpuff** [comment]
I am having the same "Error in rule classify_by_group:" error when I use either 
virsorter run -w Chicken_control_test.out -i viral_MAG_R_Chicken_control.fa --include-groups RNA -j 4 all
virsorter run -w Chicken_control_test.out -i viral_MAG_R_Chicken_control.fa --min-length 100 -j 4 all

**Comment by lbooshehri** [comment]
@jiarong - thanks so much for your help and attention to this! 
I just tried a re-run, please see log below:

(vs2) acquaboosh@Laela ~ % virsorter run -w EA25.8phage_vs2.out -i EA25.8phage.assembly.fasta_assembly.fa --min-length 1500 -j 4 all
[2023-01-17 20:00 INFO] VirSorter 2.2.3
[2023-01-17 20:00 INFO] /Users/acquaboosh/opt/anaconda3/envs/vs2/bin/virsorter run -w EA25.8phage_vs2.out -i EA25.8phage.assembly.fasta_assembly.fa --min-length 1500 -j 4 all
[2023-01-17 20:00 INFO] Using /Users/acquaboosh/opt/anaconda3/envs/vs2/lib/python3.10/site-packages/virsorter/template-config.yaml as config template
[2023-01-17 20:00 INFO] conig file written to /Users/acquaboosh/EA25.8phage_vs2.out/config.yaml

[2023-01-17 20:00 INFO] Executing: snakemake --snakefile /Users/acquaboosh/opt/anaconda3/envs/vs2/lib/python3.10/site-packages/virsorter/Snakefile --directory /Users/acquaboosh/EA25.8phage_vs2.out --jobs 4 --configfile /Users/acquaboosh/EA25.8phage_vs2.out/config.yaml --latency-wait 600 --rerun-incomplete --nolock  --conda-frontend mamba --conda-prefix /Users/acquaboosh/db/conda_envs --use-conda    --quiet  all   
Job counts:
	count	jobs
	1	all
	1	check_point_for_reclassify
	1	circular_linear_split
	1	classify
	2	classify_by_group
	2	classify_full_and_part_by_group
	1	combine_linear_circular
	2	combine_linear_circular_by_group
	1	extract_feature
	1	extract_provirus_seqs
	1	finalize
	1	gff_feature
	2	gff_feature_by_group
	2	hmm_features_by_group
	1	hmm_sort_to_best_hit_taxon
	2	hmm_sort_to_best_hit_taxon_by_group
	1	merge_classification
	1	merge_full_and_part_classification
	2	merge_hmm_gff_features_by_group
	2	merge_provirus_call_by_group_by_split
	1	merge_provirus_call_from_groups
	5	merge_split_hmmtbl
	10	merge_split_hmmtbl_by_group
	10	merge_split_hmmtbl_by_group_tmp
	1	pick_viral_fullseq
	1	preprocess
	1	split_faa
	2	split_faa_by_group
	2	split_gff_by_group
	61
[2023-01-17 20:00 INFO] # of seqs < 1500 bp and removed: 1
[2023-01-17 20:00 INFO] # of circular seqs: 0
[2023-01-17 20:00 INFO] # of linear seqs  : 4
[2023-01-17 20:00 INFO] No circular seqs found in contig file
[2023-01-17 20:00 INFO] Finish spliting linear contig file with common rbs
[2023-01-17 20:00 INFO] Step 1 - preprocess finished.
[2023-01-17 20:03 INFO] Step 2 - extract-feature finished.
[2023-01-17 20:03 ERROR] See error details in /Users/acquaboosh/EA25.8phage_vs2.out/log/iter-0/step3-classify/all-score-ssDNA.log
[2023-01-17 20:03 ERROR] See error details in /Users/acquaboosh/EA25.8phage_vs2.out/log/iter-0/step3-classify/all-score-dsDNAphage.log
[Tue Jan 17 20:03:22 2023]
[Tue Jan 17 20:03:22 2023]
Error in rule classify_by_group:
Error in rule classify_by_group:
    jobid: 56
    jobid: 57
    output: iter-0/dsDNAphage/all.pdg.clf
    output: iter-0/ssDNA/all.pdg.clf
    conda-env: /Users/acquaboosh/db/conda_envs/cdabb455
    conda-env: /Users/acquaboosh/db/conda_envs/cdabb455
    shell:
        
        Log=/Users/acquaboosh/EA25.8phage_vs2.out/log/iter-0/step3-classify/all-score-dsDNAphage.log
        python /Users/acquaboosh/opt/anaconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/classify.py iter-0/dsDNAphage/all.pdg.ftr /Users/acquaboosh/db/group/dsDNAphage/model dsDNAphage iter-0/dsDNAphage/all.pdg.clf 2> $Log || { echo "See error details in $Log" | python /Users/acquaboosh/opt/anaconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
    shell:
        
        Log=/Users/acquaboosh/EA25.8phage_vs2.out/log/iter-0/step3-classify/all-score-ssDNA.log
        python /Users/acquaboosh/opt/anaconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/classify.py iter-0/ssDNA/all.pdg.ftr /Users/acquaboosh/db/group/ssDNA/model ssDNA iter-0/ssDNA/all.pdg.clf 2> $Log || { echo "See error details in $Log" | python /Users/acquaboosh/opt/anaconda3/envs/vs2/lib/python3.10/site-packages/virsorter/./scripts/echo.py --level error; exit 1; }
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)


Exiting because a job execution failed. Look above for error message


*** An error occurred. Detailed errors may not be printed for certain rules. Refer to the log file of the failed command for troubleshooting
Issues can be raised at: https://github.com/jiarong/VirSorter2/issues
(vs2) acquaboosh@Laela ~ %

**Comment by jiarong** [comment]
@lbooshehri Thanks for the detailed info. It is actually the issue (#145) I was suspecting. I am working on fixing it w/ the bioconda version. Or you can use the apptainer/singularity version (installation option 3).

**Comment by lbooshehri** [comment]
@jiarong thanks for letting me know and for continuing to  work on the issue! I'll try out alternative options as suggested for now. Much appreciated.

**Comment by jiarong** [comment]
@lbooshehri and @liucong0429 I have updated the conda version (v.2.2.4).

**Comment by liucong0429** [comment]
thanks for your help !!!

**Comment by morganpuff** [comment]
I don't know if this is related, but I did have to install pytest and its dependencies after updating/re-installing the newest version - as a heads up. 

But - it is now working, thanks.

**Comment by lbooshehri** [comment]
Yes! It's working great now. Super appreciated! @jiarong
