### ISSUE TITLE
the parameter question(-virome) about the virsorter2

### ISSUE THREAD

**Issue by pengshuoyang** [jiarong/VirSorter2#15]
Thanks for your efforts to develope this new virsorter.In the older version of virsorter, the parameter "-virome" is used for identifiying the sequences from virome. But in the virsorter2, i donot find anything new to describe the "-virome" parameter. So i am wondering whether the virsorter could hanlde the virome data and how.

**Comment by jiarong** [comment]
VirSorter2 can handle virome. VirSorter2 works different from VirSorter1. VirSorter1 estimates global microbial genome features differently in --virome mode compared to normal mode due to lack microbial genome date in user data. For VirSorter2, there is no such difference. All models are estimated from existing known genomes.
